### ISSUE TITLE
Feature roadmap

### ISSUE THREAD

**Issue by krikun98** [FrogOfJuly/rogue-like#8]
Backend:

- [ ] Pause enemies between every move (like Crypt of the Necrodancer)
- [ ] Multiple rooms, exits
- [ ] Score tracking
- [ ] Level-dependent enemy/item spawns, with the level defining the health/damage
- [ ] Display levels for traps
- [ ] Boss that digs through walls
- [ ] Entrances, spawn players close to each other?

Server:

- [ ] Disconnect/potentially replace dead players
- [x] API documentation

Client:

- [x] Proper level/health dependent color system
- [ ] Allow for help, pause, exit and legend commands while waiting (may not be possible with current implementation)
- [ ] Inventory description in help
- [ ] Alternative clients (Telegram bot?)
- [ ] Display item stat bonuses
- [ ] Level-to-color map in help
